= Tortuga
Miguel D. Salcedo <miguel@salcedo.cc>
:toc:
:sectanchors:

[NOTE]
.Key words for use in RFCs to Indicate Requirement Levels
====
The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL
NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED",  "MAY", and
"OPTIONAL" in this document are to be interpreted as described in
RFC 2119.
====

[abstract]
== Abstract
Tortuga is an actor-based programming language and runtime. The runtime is written in Rust to provide performance and memory safety, while the language compiles to WebAssembly.

== WebAssembly
This project defines WebAssembly as a language in MPS in order to build a Tortuga language workbench on top. The language implementation adheres to the https://webassembly.github.io/spec/core/text/index.html[text format] of the specification, but leaves out parts not relevant to Tortuga (such as abbreviated formats for various definitions).

== Language
The Tortuga language is comprised of 3 core concepts: systems, actors, and messages. These concepts are used to define the core logic of any distributed system.

=== System
A system in Tortuga is the unit of deployment. Implementors need not guarantee backwards compatibility between actors in the same system as the entire system is updated at once. However, backwards compatibility MUST be maintained between versions of the same system.

Deployments of a system occur by updating the system with new versions of each actor in the system. The runtime, then instantiates a new system, drains the current continuations in the old version that are processing messages, and switches over all message queues to the new system atomically. Thus, new versions of the system MUST be able to process messages intended for older versions.

A single root actor defines the supervision tree hierarchy. Tortuga only allows a single root actor to encourage independent modules to be their own systems. Inter-system communication is the same whether the systems are on the same machine or across the world from each other. Also, a single root actor encourages systems that do a single thing and do it well; a guiding principle of UNIX programs.

=== Actor
TODO

=== Messages
TODO