package WebAssembly.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_ValueTypes extends EnumerationDescriptorBase {

  public EnumerationDescriptor_ValueTypes() {
    super(0x3858ffa4421444acL, 0x99984ee1e7b8b797L, 0x1e186fe05c7a4625L, "ValueTypes", "r:c0f59883-361d-4b09-be24-39e7ad8052de(WebAssembly.structure)/2168606229993768485");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_i32_0 = new EnumerationDescriptor.MemberDescriptor("i32", "i32", 0x1e186fe05c7a4626L, "r:c0f59883-361d-4b09-be24-39e7ad8052de(WebAssembly.structure)/2168606229993768486");
  private final EnumerationDescriptor.MemberDescriptor myMember_i64_0 = new EnumerationDescriptor.MemberDescriptor("i64", "i64", 0x1e186fe05c7a4627L, "r:c0f59883-361d-4b09-be24-39e7ad8052de(WebAssembly.structure)/2168606229993768487");
  private final EnumerationDescriptor.MemberDescriptor myMember_f32_0 = new EnumerationDescriptor.MemberDescriptor("f32", "f32", 0x1e186fe05c7a462aL, "r:c0f59883-361d-4b09-be24-39e7ad8052de(WebAssembly.structure)/2168606229993768490");
  private final EnumerationDescriptor.MemberDescriptor myMember_f64_0 = new EnumerationDescriptor.MemberDescriptor("f64", "f64", 0x1e186fe05c7a462eL, "r:c0f59883-361d-4b09-be24-39e7ad8052de(WebAssembly.structure)/2168606229993768494");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x3858ffa4421444acL, 0x99984ee1e7b8b797L, 0x1e186fe05c7a4625L, 0x1e186fe05c7a4626L, 0x1e186fe05c7a4627L, 0x1e186fe05c7a462aL, 0x1e186fe05c7a462eL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_i32_0, myMember_i64_0, myMember_f32_0, myMember_f64_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "i32":
        return myMember_i32_0;
      case "i64":
        return myMember_i64_0;
      case "f32":
        return myMember_f32_0;
      case "f64":
        return myMember_f64_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
