package WebAssembly.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SContainmentLink;

public class Import_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.newLine();
    tgs.indent();
    tgs.append("(import \"");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.module$ZHJl));
    tgs.append("\" \"");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.function$ZIdn));
    tgs.append("\" (func");
    tgs.appendNode(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.signature$2c$U));
    tgs.append("))");
  }

  private static final class PROPS {
    /*package*/ static final SProperty module$ZHJl = MetaAdapterFactory.getProperty(0x3858ffa4421444acL, 0x99984ee1e7b8b797L, 0x6dd923024fe00a4eL, 0x6dd923024fe00a4fL, "module");
    /*package*/ static final SProperty function$ZIdn = MetaAdapterFactory.getProperty(0x3858ffa4421444acL, 0x99984ee1e7b8b797L, 0x6dd923024fe00a4eL, 0x6dd923024fe00a51L, "function");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink signature$2c$U = MetaAdapterFactory.getContainmentLink(0x3858ffa4421444acL, 0x99984ee1e7b8b797L, 0x6dd923024fe00a4eL, 0x6dd923024fe00a54L, "signature");
  }
}
