package WebAssembly.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class Parameter_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append(" (param ");
    tgs.append(SPropertyOperations.getEnum(ctx.getPrimaryInput(), PROPS.type$egLy).getPresentation());
    tgs.append(")");
  }

  private static final class PROPS {
    /*package*/ static final SProperty type$egLy = MetaAdapterFactory.getProperty(0x3858ffa4421444acL, 0x99984ee1e7b8b797L, 0x1759765b97fc1f1L, 0x1e186fe05c7a46bcL, "type");
  }
}
